---
title: Stacked Data Matrices Workshop
subtitle: EES 2019 Italian Voter Study - Stacked Dataset Codebook
author: Giuseppe Carteny
date: 31.05.2021 
toc: true
output: 
  bookdown::pdf_document2:
    includes:
      in_header: rmd_inheader.tex
urlcolor: blue
---

\newpage
# Overview {-}

This document consists in the codebook of the stacked European Election Studies (EES) Italian voter study of 2019 as created by the scripts provided for the workshop. The logic and structure of the codebook resembles those of the True European Voter (TEV) codebook. The variables available in the dataset are grouped as it follows: 

* Identification Variables 
* Voting Behaviour and Background Variables
* Voter-Party Positional Variables
* Generic and Synthetic Variables


# Identification Variables {-}

## respid {-}
Unique identifier of individual respondents as it was assigned in the EES 2019 Italian voter study (`respid`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)).

## party {-}
Unique identifier of the Italian parties participating to the European Parliament (EP) elections of 2019. Values equate to those defined in the original EES 2019 vote choice variable referring to the 2019 EP elections (`Q7`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)). Only parties for which propensity to vote (PTV) variables where available in the EES 2019 Italian voter study have been selected. 

Values: 

1501 - Democratic Party (*Partito Democratico*)  
1502 - Go Italy (*Forza Italia*)  
1503 - Northern League (*Lega - Salvini Premier*)  
1504 - Five Star Movement (*Movimento 5 Stelle*)  
1505 - Italian Left (*Sinistra Italiana*)  
1506 - More Europe (*+Europa*)  
1507 - Brothers of Italy (*Fratelli d'Italia*)  

99 - Missing

## stackid {-}
Unique identifier of party-voter dyadic relationships. It represents the combination of EES 2019 Italian voter study (1) respondents' identification numbers (`respid`) and (2) party unique identifier variable (`party`). 

Example: The dyad referring to the relationship between the respondent identified by the number 778 and the Italian Democratic Party (*Partito Democratico*; code 1501) would be '778-1501'. 


```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=F}

library(knitr)
library(kableExtra)

options(knitr.kable.NA = '')
options(knitr.table.format = "latex")

df <- 
  data.frame(
  'pname_it' = c('Partito Democratico', 'Forza Italia', 
                        'Lega - Salvini Premier', 'Movimento 5 Stelle', 
                        'Sinistra Italiana', '+Europa', 
                        "Fratelli d'Italia - Centrodestra Nazionale"),
  'pname_en' = c('Democratic Party', 'Go Italy', 
                        'Northern League', 'Five Star Movement', 
                        'Italian Left', 'More Europe', 
                        "Brothers of Italy - National Centre-right"),
  'pcode' = c(1501:1507)
)

names(df) <- c('Party Name (it)', 'Party Name (en)', 'Party Code')

df %>%
  knitr::kable(format="latex", longtable = F, # caption = "List of Parties Available in the Dataset",
               booktabs=T, linesep = "", align = c('l','l','c')) %>%
  kable_classic()


```

# Voting Behaviour and Background Variables {-}

## votech {-}
EES 2019 original vote choice variable, referring to 2019 EP elections respondents' self reported vote choice (`Q7`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)). 

Values: 

1501 - Democratic Party (*Partito Democratico*)  
1502 - Go Italy (*Forza Italia*)  
1503 - Northern League (*Lega - Salvini Premier*)  
1504 - Five Star Movement (*Movimento 5 Stelle*)  
1505 - Italian Left (*Sinistra Italiana*)  
1506 - More Europe (*+Europa*)  
1507 - Brothers of Italy (*Fratelli d'Italia*)  

99 - Missing OR did not vote OR voted for another party

## pid {-}
EES 2019 party identification variable (`Q25`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)), recoded according to the 2019 European Parliament (EP) Elections vote choice variable values (`Q7`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)). 

Example:
In the EES 2019 voter study, the party code of the 2019 EP elections vote choice variable (`Q7`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)) that refers to the Italian Democratic Party (*Partito Democratico*) is `1501`. However, in the party identification variable of the EES 2019 voter study  (`Q25`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)) the Italian Democratic Party is coded `1502`. Consequently, the choice has been to recode the latter in accordance with the former.

Values:

1501 - Does identify with political party 1501  
...   
1507 - Does identify with political party 1507  

99 - Missing OR does not identify with any relevant political party (see `party`)

## pid_str {-}
Recoded EES 2019 original variable indicating the respondent strength of party identification (`Q25`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)) with the party specified in `pid` variable. 

Values: 

1 - Merely a sympathiser  
2 - Fairly close  
3 - Very close to the party  

99 - Missing OR does not identify with any relevant political party (see `party`)

## age {-}
Age of the respondents. Computed by substracting the EES 2019 respondents' birth year variable (`D4_1`) to the survey year (2019). 

Values: 

999 - Missing


## gndr {-}
The gender of the respondent, recoded from the original EES 2019 gender variable (`D3`). Recoded from the original in order to create a dichotomous variable given the low number of respondents part of the original category 'Other' (2 observations for the EES 2019 Italian voter study).

Values:

1 - Male  
2 - Female

99 - Missing


## edu {-}
Years of education of the respondent, recoded from the original EES 2019 education variable (`EDU`).

Values: 

1 - 15 years and less  
2 - 16-19 years  
3 - 20+ years

99 - Missing


# Voter-Party Positional Variables {-}

## lr_self {-}
Respondent Left-Right self placement measure, rescaled for the original EES 2019 variable (`Q11`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)).

Values: 

0 - Left  
...  
1 - Right

99 - Missing  


## lr_party {-}
Left-Right position of the stack party (identified by the `party` variable). Created computing the mean of all the EES respondents' perceptions of each relevant party position on the left–right dimension (Prefix: `Q13_`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448).

Values: 

0 - Left  
...  
1 - Right

99 - Missing  

## lr_party_ches {-}
Left-Right position of the stack party (identified by the `party` variable) based on 1999-2019 Chapel Hill Experts Survey (CHES) data (`lrgen`; See the [1999-2019 CHES Codebook](https://www.chesdata.eu/s/1999-2019_CHES_codebook.pdf)).

Values: 

0 - Left  
...  
1 - Right

99 - Missing  

## euint_self  {-}
Respondent attitude toward the European Union (EU) integration process. Rescaled for the original EES 2019 variable (`Q23`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)).

Values: 

0 - EU integration^[In the original [EES 2019 Master Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=67447) reference is made to EU *unification* rather than *integration* process. Nonetheless, the two concepts can be considered almost equivalent.] has already gone too far  
...  
1 - EU integration should be pushed further

99 - Missing  


## euint_party  {-}
Position about the European Union (EU) integration process of the stack party (identified by the `party` variable). Created computing the mean of all the EES respondents' perceptions of each relevant party position about the EU integration process (Prefix: `Q24_`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)).

Values: 

0 - Against further EU integration  
...  
1 - Supporting EU integration 

99 - Missing  

## euint_party_ches  {-}
Position about the European Union (EU) integration process of the stack party (identified by the `party` variable) based on 1999-2019 Chapel Hill Experts Survey (CHES) data (`eu_position`; See the [1999-2019 CHES Codebook](https://www.chesdata.eu/s/1999-2019_CHES_codebook.pdf)).

Values: 

0 - Against further EU integration  
...  
1 - Supporting EU integration 

99 - Missing  


# Generic and Synthetic Variables {-}


## ptv {-}
The degree of propensity to vote (PTV) for the stack party (`party`). Rescaled from the EES 2019 PTV variables (Prefix: `Q10_`; See the [EES2019 Codebook](https://dbk.gesis.org/dbksearch/download.asp?id=67448)).

Values: 
 
0 - Very low  
...  
1 - Very high  

99 - Missing


## stacked_votech {-}
Dichotomous vote choice variable, measuring whether the respondent voted for the stack party (`party`). Recoded from the EES 2019 original vote choice variable (`votech`).

Values: 

0 - Did not vote for the stack party  
1 - Did vote for the stack party

99 - Missing


## stacked_pid {-}
Dichotomous vote choice variable, measuring whether the respondent identifies with the stack party (`party`). Recoded from the party identification variable (`pid`).

Values: 

0 - Does not identify with the stack party  
1 - Does identify with the stack party

99 - Missing OR does not identify with any relevant political party (see `party`)


## stacked_pid_str {-}
Measure of the strength of the respondent identification with the stack party (`party`). Recoded from the party identification strength variable (`pid_str`).

Values: 

1 - Merely a sympathiser of the stack party
2 - Fairly close to the stack party
3 - Very close to the stack party 

99 - Missing OR does not identify with any relevant political party (see `party`)


## lr_dist  {-}
Distance between respondent and the stack party (`party`) on the Left-Right dimension. This variable is the absolute difference of the respondent Left-Right self placement measure (`lr_self`) and the party positions on the same *continuum* (`lr_party`). 

Values: 

0 - Minimum distance between respondent and stack party  
...  
1 - Maximum distance between respondent and stack party  

99 - Missing


## lr_dist_ches {-}
Distance between respondent and the stack party (`party`) on the Left-Right dimension. This variable is the absolute difference of the respondent Left-Right self placement measure (`lr_self`) and the party positions on the same *continuum* as defined by the variable based on 1999-2019 Chapel Hill Experts Survey (CHES) data (`lr_party_ches`). 

Values: 

0 - Minimum distance between respondent and stack party  
...  
1 - Maximum distance between respondent and stack party  

99 - Missing

## euint_dist {-}
Distance between respondent and the stack party about the European Union (EU) integration process. This variable is the absolute difference of the respondent attitude toward the European Union integration process. (`euint_self`) and the party positions on the same *continuum* (`euint_party`). 

Values: 

0 - Minimum distance between respondent and stack party  
...  
1 - Maximum distance between respondent and stack party  

99 - Missing


## euint_dist_ches {-}
Distance between respondent and the stack party (`party`) about the European Union (EU) integration process. This variable is the absolute difference of the respondent attitude toward the European Union integration process. (`euint_self`) and the party positions on the same *continuum* as defined by the variable based on 1999-2019 Chapel Hill Experts Survey (CHES) data (`euint_party_ches`). 

Values: 

0 - Minimum distance between respondent and stack party  
...  
1 - Maximum distance between respondent and stack party  

99 - Missing


## age_dich_yhat {-}
Y-hats, calculated by way of binary logistic regressions in the form of predicted probabilities of voting for the stack party (`votech`) on the basis of the respondent age variable (`age`). They are not centered.

Values: 

0  
...  
1

99 - Missing


## age_cont_yhat {-}
Y-hats, calculated by way of Ordinary Least Squares (OLS) regressions in the form of linear predictions of the degree of propensity to vote for the stack party (`ptv`) on the basis of the respondent age variable (`age`). They are not centered.

Values: 

0  
...  
1

99 - Missing

## socdem_dich_yhat {-}
Y-hats, calculated by way of binary logistic regressions in the form of predicted probabilities of voting for the stack party (`votech`) on the basis of respondents' age (`age`), gender (`gndr`), and education (`edu`) variables. They are not centered.

Values: 

0  
...  
1

99 - Missing



## socdem_cont_yhat {-}
Y-hats, calculated by way of Ordinary Least Squares (OLS) regressions in the form of linear predictions of the degree of propensity to vote for the stack party (`ptv`) on the basis of respondents' age (`age`), gender (`gndr`), and education (`edu`) variables. They are not centered.

Values: 

0  
...  
1

99 - Missing
